### ISSUE TITLE
critical error when installing meson-python 0.16.0 with mamba

### ISSUE THREAD

**Issue by rgommers** [conda-forge/meson-python-feedstock#21]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Encountered when creating a new environment with `mamba create`. Unclear to me whether this is an issue with this feedstock or with `mamba`:
```
critical libmamba Pathname can't be converted from UTF-8 to current locale.
error    libmamba Error opening for reading "/home/rgommers/mambaforge/pkgs/meson-python-0.16.0-pyh0c530f3_0/info/index.json": No such file or directory
error    libmamba Error when extracting package: [json.exception.parse_error.101] parse error at limeson-python                                        71.4kB @   7.1kB/s  0.5s
meson-python-0.16.0-pyh0c530f3_0.conda extraction failed
...
Found incorrect download: meson-python. Aborting
```
Never seen anything like that before. Full terminal output:

```
$ mamba create -n openblas-wheel compilers pkg-config meson-python ninja 

Looking for: ['compilers', 'pkg-config', 'meson-python', 'ninja']

conda-forge/noarch                                  16.7MB @ 379.1kB/s 44.1s
conda-forge/linux-64                                39.8MB @ 570.1kB/s 1m:10.1s
Transaction

  Prefix: /home/rgommers/mambaforge/envs/openblas-wheel

  Updating specs:

   - compilers
   - pkg-config
   - meson-python
   - ninja


  Package                          Version  Build               Channel                    Size
─────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex                      0.1  conda_forge         conda-forge/linux-64     Cached
  + _openmp_mutex                      4.5  2_gnu               conda-forge/linux-64     Cached
  + binutils                          2.40  h4852527_0          conda-forge/linux-64       31kB
  + binutils_impl_linux-64            2.40  ha885e6a_0          conda-forge/linux-64        6MB
  + binutils_linux-64                 2.40  hdade7a5_3          conda-forge/linux-64     Cached
  + bzip2                            1.0.8  hd590300_5          conda-forge/linux-64     Cached
  + c-compiler                       1.7.0  hd590300_0          conda-forge/linux-64     Cached
  + ca-certificates               2024.2.2  hbcca054_0          conda-forge/linux-64     Cached
  + compilers                        1.7.0  ha770c72_0          conda-forge/linux-64     Cached
  + cxx-compiler                     1.7.0  h00ab1b0_0          conda-forge/linux-64     Cached
  + fortran-compiler                 1.7.0  heb67821_0          conda-forge/linux-64     Cached
  + gcc                             12.3.0  h915e2ae_6          conda-forge/linux-64       26kB
  + gcc_impl_linux-64               12.3.0  h1562d66_6          conda-forge/linux-64       52MB
  + gcc_linux-64                    12.3.0  h6477408_3          conda-forge/linux-64     Cached
  + gfortran                        12.3.0  h915e2ae_6          conda-forge/linux-64       25kB
  + gfortran_impl_linux-64          12.3.0  h6d6b2fb_6          conda-forge/linux-64       15MB
  + gfortran_linux-64               12.3.0  h617cb40_3          conda-forge/linux-64     Cached
  + gxx                             12.3.0  h915e2ae_6          conda-forge/linux-64       25kB
  + gxx_impl_linux-64               12.3.0  h1562d66_6          conda-forge/linux-64       13MB
  + gxx_linux-64                    12.3.0  h4a1b8e8_3          conda-forge/linux-64     Cached
  + kernel-headers_linux-64         2.6.32  he073ed8_17         conda-forge/noarch       Cached
  + ld_impl_linux-64                  2.40  h55db66e_0          conda-forge/linux-64      713kB
  + libexpat                         2.6.2  h59595ed_0          conda-forge/linux-64     Cached
  + libffi                           3.4.2  h7f98852_5          conda-forge/linux-64     Cached
  + libgcc-devel_linux-64           12.3.0  h2af2641_106        conda-forge/noarch          3MB
  + libgcc-ng                       13.2.0  hc881cc4_6          conda-forge/linux-64      777kB
  + libgfortran5                    13.2.0  h43f5ff8_6          conda-forge/linux-64        1MB
  + libgomp                         13.2.0  hc881cc4_6          conda-forge/linux-64      422kB
  + libnsl                           2.0.1  hd590300_0          conda-forge/linux-64     Cached
  + libsanitizer                    12.3.0  h2af2641_6          conda-forge/linux-64        4MB
  + libsqlite                       3.45.3  h2797004_0          conda-forge/linux-64      860kB
  + libstdcxx-devel_linux-64        12.3.0  h2af2641_106        conda-forge/noarch         12MB
  + libstdcxx-ng                    13.2.0  h95c4c6d_6          conda-forge/linux-64        4MB
  + libuuid                         2.38.1  h0b41bf4_0          conda-forge/linux-64     Cached
  + libxcrypt                       4.4.36  hd590300_1          conda-forge/linux-64     Cached
  + libzlib                         1.2.13  hd590300_5          conda-forge/linux-64     Cached
  + meson                            1.4.0  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + meson-python                    0.16.0  pyh0c530f3_0        conda-forge/noarch         71kB
  + ncurses                   6.4.20240210  h59595ed_0          conda-forge/linux-64     Cached
  + ninja                           1.12.0  h00ab1b0_0          conda-forge/linux-64        2MB
  + openssl                          3.2.1  hd590300_1          conda-forge/linux-64     Cached
  + packaging                         24.0  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + pip                               24.0  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + pkg-config                      0.29.2  h36c2ea0_1008       conda-forge/linux-64     Cached
  + pyproject-metadata               0.8.0  pyhd8ed1ab_0        conda-forge/noarch         13kB
  + python                          3.12.3  hab00c5b_0_cpython  conda-forge/linux-64       32MB
  + readline                           8.2  h8228510_1          conda-forge/linux-64     Cached
  + setuptools                      69.5.1  pyhd8ed1ab_0        conda-forge/noarch        502kB
  + sysroot_linux-64                  2.12  he073ed8_17         conda-forge/noarch       Cached
  + tk                              8.6.13  noxft_h4845f30_101  conda-forge/linux-64     Cached
  + tomli                            2.0.1  pyhd8ed1ab_0        conda-forge/noarch       Cached
  + tzdata                           2024a  h0c530f3_0          conda-forge/noarch       Cached
  + wheel                           0.43.0  pyhd8ed1ab_1        conda-forge/noarch       Cached
  + xz                               5.2.6  h166bdaf_0          conda-forge/linux-64     Cached

  Summary:

  Install: 54 packages

  Total download: 147MB

─────────────────────────────────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] 
libgomp                                            422.4kB @ 209.6kB/s  2.0s
ld_impl_linux-64                                   713.3kB @ 322.8kB/s  2.2s
libgcc-ng                                          777.3kB @ 245.8kB/s  3.2s
gcc                                                 26.0kB @   7.6kB/s  0.3s
libgfortran5                                         1.4MB @ 314.4kB/s  4.6s
setuptools                                         501.8kB @  89.1kB/s  2.2s
libstdcxx-ng                                         3.8MB @ 428.3kB/s  9.0s
binutils                                            31.1kB @   3.3kB/s  0.4s
gxx                                                 25.5kB @   2.7kB/s  0.2s
[+] 10.0s
Downloading  (5) ━╸━━━━━━━━━━━━━╸━━━━  16.0MB / 147.0MB @   1.4MB/s python                    10.0s
Extracting       ━━━━━━━╸━━━━━━━╸━━━━       9 /      22                                        0.3scritical libmamba Pathname can't be converted from UTF-8 to current locale.
error    libmamba Error opening for reading "/home/rgommers/mambaforge/pkgs/meson-python-0.16.0-pyh0c530f3_0/info/index.json": No such file or directory
error    libmamba Error when extracting package: [json.exception.parse_error.101] parse error at limeson-python                                        71.4kB @   7.1kB/s  0.5s
meson-python-0.16.0-pyh0c530f3_0.conda extraction failed
libsanitizer                                         3.9MB @ 244.9kB/s 11.5s
libgcc-devel_linux-64                                2.5MB @ 102.6kB/s 14.7s
ninja                                                2.2MB @  64.6kB/s  9.6s
libstdcxx-devel_linux-64                            12.0MB @ 219.0kB/s 49.1s
libsqlite                                          859.9kB @  14.7kB/s  3.8s
pyproject-metadata                                  13.2kB @ 224.0 B/s  0.3s
gxx_impl_linux-64                                   12.7MB @ 212.8kB/s 43.6s
gfortran                                            25.5kB @ 426.0 B/s  0.2s
binutils_impl_linux-64                               5.8MB @  63.6kB/s 32.4s
gfortran_impl_linux-64                              15.4MB @ 166.2kB/s 58.3s
python                                              32.0MB @ 291.6kB/s 1m:47.7s
gcc_impl_linux-64                                   51.7MB @ 338.8kB/s 2m:30.5s
Found incorrect download: meson-python. Aborting

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/rgommers/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1125, in __call__
        return func(*args, **kwargs)
      File "/home/rgommers/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 935, in exception_converter
        raise e
      File "/home/rgommers/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 928, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/rgommers/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 886, in _wrapped_main
        result = do_call(args, p)
      File "/home/rgommers/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 754, in do_call
        exit_code = create(args, parser)
      File "/home/rgommers/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 630, in create
        return install(args, parser, "create")
      File "/home/rgommers/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 586, in install
        transaction.fetch_extract_packages()
    RuntimeError: Found incorrect download: meson-python. Aborting

`$ /home/rgommers/mambaforge/bin/mamba create -n openblas-wheel compilers pkg-config meson-python ninja`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/rgommers/mambaforge/bin/conda
             CONDA_PREFIX=/home/rgommers/mambaforge
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/rgommers/mambaforge/bin/python
               CONDA_ROOT=/home/rgommers/mambaforge
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/rgommers/mambaforge/bin:/home/rgommers/mambaforge/bin:/home/rgom
                          mers/mambaforge/condabin:/home/rgommers/.nix-profile/bin:/nix/var/nix/
                          profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/
                          jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_
                          perl:/home/rgommers/.pixi/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1

     active environment : base
    active env location : /home/rgommers/mambaforge
            shell level : 1
       user config file : /home/rgommers/.condarc
 populated config files : /home/rgommers/mambaforge/.condarc
          conda version : 4.14.0
    conda-build version : not installed
         python version : 3.10.6.final.0
       virtual packages : __cuda=12.3=0
                          __linux=6.7.6=0
                          __glibc=2.39=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/rgommers/mambaforge  (writable)
      conda av data dir : /home/rgommers/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/rgommers/mambaforge/pkgs
                          /home/rgommers/.conda/pkgs
       envs directories : /home/rgommers/mambaforge/envs
                          /home/rgommers/.conda/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.28.1 CPython/3.10.6 Linux/6.7.6-arch1-1 endeavouros/rolling glibc/2.39
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

### Installed packages

```shell
n/a
```

### Environment info

<details>

```shell
$ conda info

     active environment : base
    active env location : /home/rgommers/mambaforge
            shell level : 1
       user config file : /home/rgommers/.condarc
 populated config files : /home/rgommers/mambaforge/.condarc
          conda version : 4.14.0
    conda-build version : not installed
         python version : 3.10.6.final.0
       virtual packages : __cuda=12.3=0
                          __linux=6.7.6=0
                          __glibc=2.39=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/rgommers/mambaforge  (writable)
      conda av data dir : /home/rgommers/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/rgommers/mambaforge/pkgs
                          /home/rgommers/.conda/pkgs
       envs directories : /home/rgommers/mambaforge/envs
                          /home/rgommers/.conda/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.28.1 CPython/3.10.6 Linux/6.7.6-arch1-1 endeavouros/rolling glibc/2.39
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

</details>

**Comment by rgommers** [comment]
Probably a `mamba` issue, since `conda` works fine here. `meson-python` 0.15.0 also works fine with `mamba`.

**Comment by awvwgk** [comment]
The CI is pulling this release https://github.com/conda-forge/miniforge/releases/tag/22.9.0-3 with mamba 1.1.0
